default_platform(:ios)

platform :ios do
  desc "Build and deploy to staging"
  lane :ios_staging do
    tag_name = ENV['TAG_NAME']
    puts "Tag received: #{tag_name}"
    if tag_name =~ /^\d+\.\d+\.\d+(-rc\.\d+)?(\+\d+)?$/
      UI.message("Building and deploying to Staging for tag: #{tag_name}")
      # Add your iOS build commands here
    else
      UI.message("Invalid tag format for Staging: #{tag_name}")
    end
  end
end