name: Charge+ Customer Workflow
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  prepare_environment:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  android_staging:
    name: Android (Staging)
    runs-on: ubuntu-latest
    # if: github.ref matches '^(refs/tags/)?\d+\.\d+\.\d+(-(?:alpha|beta|rc)\.\d+)?\+\d+$'
    needs: prepare_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check tag validity
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+|-beta\.[0-9]+|-rc\.[0-9]+)?\+[0-9]+$ ]]; then
            echo "Valid tag: $TAG_NAME"
          else
            echo "Invalid tag: $TAG_NAME"
            exit 1
          fi

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  # ios_staging:
  #   name: iOS (Staging)
  #   runs-on: macos-14
  #   if: github.ref matches '^(refs/tags/)?\d+\.\d+\.\d+(-(?:alpha|beta|rc)\.\d+)?\+\d+$'
  #   needs: prepare_environment
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Print tag information
  #       run: | 
  #         TAG_NAME=${GITHUB_REF#refs/tags/}
  #         echo "Tag: $TAG_NAME"