name: Charge+ Customer Workflow
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  prepare_environment:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"
          if [[ "$TAG_NAME" =~ dev ]]; then
            echo "Tag contains 'dev'. Exiting workflow."
            exit 1
          fi

  android_staging:
    name: Android (Staging)
    runs-on: ubuntu-latest
    needs: prepare_environment
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  android_production:
    name: Android (Production)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: prepare_environment
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  huawei_production:
    name: Android (Huawei AppGallery)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: prepare_environment
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  ios_staging:
    name: iOS (Staging)
    runs-on: macos-14
    needs: prepare_environment
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set TAG_NAME environment variable
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # This sets TAG_NAME for use in the Fastfile
          echo "Fastlane will use TAG_NAME=$TAG_NAME"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify the Ruby version required by Fastlane

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Run Fastlane ios_staging
        env:
          TAG_NAME: ${{ env.TAG_NAME }}  # Passing the TAG_NAME environment variable into Fastlane
        run: |
          bundle exec fastlane ios_staging