name: Charge+ Customer Workflow
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  prepare_environment:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  android_staging:
    name: Android (Staging)
    runs-on: ubuntu-latest
    needs: prepare_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  android_production:
    name: Android (Production)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: prepare_environment
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  huawei_production:
    name: Android (Huawei AppGallery)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: prepare_environment
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"

  ios_staging:
    name: iOS (Staging)
    runs-on: macos-14
    needs: prepare_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print tag information
        run: | 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG_NAME"